project_id             = "devops-504816"
region                 = "us-central1"
cluster_name           = "devops-gke"
environment            = "dev"
machine_type           = "e2-small" # Changed from n1-standard-2
node_count             = 1          # Changed from 2
min_nodes              = 1          # Changed from 2
max_nodes              = 2          # Changed from 5
preemptible            = true       # Added: cheaper nodes
artifact_registry_repo = "devops-images"
